//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class SendGoalResponse : Message
    {
        public const string k_RosMessageName = "remora_interfaces/SendGoal";
        public override string RosMessageName => k_RosMessageName;

        //  Response - Acknowledgment
        public bool accepted;
        public string message;

        public SendGoalResponse()
        {
            this.accepted = false;
            this.message = "";
        }

        public SendGoalResponse(bool accepted, string message)
        {
            this.accepted = accepted;
            this.message = message;
        }

        public static SendGoalResponse Deserialize(MessageDeserializer deserializer) => new SendGoalResponse(deserializer);

        private SendGoalResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.accepted);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.accepted);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SendGoalResponse: " +
            "\naccepted: " + accepted.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
