//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Action
{
    [Serializable]
    public class GoalInfoMsg : Message
    {
        public const string k_RosMessageName = "action_msgs/GoalInfo";
        public override string RosMessageName => k_RosMessageName;

        //  Goal ID
        public UniqueIdentifier.UUIDMsg goal_id;
        //  Time when the goal was accepted
        public BuiltinInterfaces.TimeMsg stamp;

        public GoalInfoMsg()
        {
            this.goal_id = new UniqueIdentifier.UUIDMsg();
            this.stamp = new BuiltinInterfaces.TimeMsg();
        }

        public GoalInfoMsg(UniqueIdentifier.UUIDMsg goal_id, BuiltinInterfaces.TimeMsg stamp)
        {
            this.goal_id = goal_id;
            this.stamp = stamp;
        }

        public static GoalInfoMsg Deserialize(MessageDeserializer deserializer) => new GoalInfoMsg(deserializer);

        private GoalInfoMsg(MessageDeserializer deserializer)
        {
            this.goal_id = UniqueIdentifier.UUIDMsg.Deserialize(deserializer);
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal_id);
            serializer.Write(this.stamp);
        }

        public override string ToString()
        {
            return "GoalInfoMsg: " +
            "\ngoal_id: " + goal_id.ToString() +
            "\nstamp: " + stamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
