//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.UniqueIdentifier;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoToPositionGetResultRequest : Message
    {
        // public const string k_RosMessageName = "remora_interfaces/GoToPosition_GetResult_Request";
        public const string k_RosMessageName = "remora_interfaces/action/_go_to_position/GoToPosition_GetResult_Request";
        public override string RosMessageName => k_RosMessageName;

        public UUIDMsg goal_id;

        public GoToPositionGetResultRequest()
        {
            this.goal_id = new UUIDMsg();
        }

        public GoToPositionGetResultRequest(UUIDMsg goal_id)
        {
            this.goal_id = goal_id;
        }

        public static GoToPositionGetResultRequest Deserialize(MessageDeserializer deserializer) => new GoToPositionGetResultRequest(deserializer);

        private GoToPositionGetResultRequest(MessageDeserializer deserializer)
        {
            this.goal_id = UUIDMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal_id);
        }

        public override string ToString()
        {
            return "GoToPositionGetResultRequest: " +
                   "\ngoal_id: " + goal_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}