//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.UniqueIdentifier;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoToPositionSendGoalRequest : Message
    {
        // public const string k_RosMessageName = "remora_interfaces/GoToPosition_SendGoal_Request";
        public const string k_RosMessageName = "remora_interfaces/action/_go_to_position/GoToPosition_SendGoal_Request";
        public override string RosMessageName => k_RosMessageName;

        public UUIDMsg goal_id;
        public GoToPositionGoal goal;

        public GoToPositionSendGoalRequest()
        {
            this.goal_id = new UUIDMsg();
            this.goal = new GoToPositionGoal();
        }

        public GoToPositionSendGoalRequest(UUIDMsg goal_id, GoToPositionGoal goal)
        {
            this.goal_id = goal_id;
            this.goal = goal;
        }

        public static GoToPositionSendGoalRequest Deserialize(MessageDeserializer deserializer) => new GoToPositionSendGoalRequest(deserializer);

        private GoToPositionSendGoalRequest(MessageDeserializer deserializer)
        {
            this.goal_id = UUIDMsg.Deserialize(deserializer);
            this.goal = GoToPositionGoal.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal_id);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "GoToPositionSendGoalRequest: " +
                   "\ngoal_id: " + goal_id.ToString() +
                   "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}