//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoToPositionSendGoalResponse : Message
    {
        // public const string k_RosMessageName = "remora_interfaces/GoToPosition_SendGoal_Response";
        public const string k_RosMessageName = "remora_interfaces/action/_go_to_position/GoToPosition_SendGoal_Response";
        public override string RosMessageName => k_RosMessageName;

        public bool accepted;
        public TimeMsg stamp;

        public GoToPositionSendGoalResponse()
        {
            this.accepted = false;
            this.stamp = new TimeMsg();
        }

        public GoToPositionSendGoalResponse(bool accepted, TimeMsg stamp)
        {
            this.accepted = accepted;
            this.stamp = stamp;
        }

        public static GoToPositionSendGoalResponse Deserialize(MessageDeserializer deserializer) => new GoToPositionSendGoalResponse(deserializer);

        private GoToPositionSendGoalResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.accepted);
            this.stamp = TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.accepted);
            serializer.Write(this.stamp);
        }

        public override string ToString()
        {
            return "GoToPositionSendGoalResponse: " +
                   "\naccepted: " + accepted.ToString() +
                   "\nstamp: " + stamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}