//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoToPositionGetResultResponse : Message
    {
        // public const string k_RosMessageName = "remora_interfaces/GoToPosition_GetResult_Response";
        public const string k_RosMessageName = "remora_interfaces/action/_go_to_position/GoToPosition_GetResult_Response";
        public override string RosMessageName => k_RosMessageName;

        public sbyte status;
        public GoToPositionResult result;

        public GoToPositionGetResultResponse()
        {
            this.status = 0;
            this.result = new GoToPositionResult();
        }

        public GoToPositionGetResultResponse(sbyte status, GoToPositionResult result)
        {
            this.status = status;
            this.result = result;
        }

        public static GoToPositionGetResultResponse Deserialize(MessageDeserializer deserializer) => new GoToPositionGetResultResponse(deserializer);

        private GoToPositionGetResultResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            this.result = GoToPositionResult.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "GoToPositionGetResultResponse: " +
                   "\nstatus: " + status.ToString() +
                   "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}