//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.UniqueIdentifier;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoToPositionFeedbackMessage : Message
    {
        // public const string k_RosMessageName = "remora_interfaces/GoToPosition_FeedbackMessage";
        public const string k_RosMessageName = "remora_interfaces/action/_go_to_position/GoToPosition_FeedbackMessage";
        public override string RosMessageName => k_RosMessageName;

        public UUIDMsg goal_id;
        public GoToPositionFeedback feedback;

        public GoToPositionFeedbackMessage()
        {
            this.goal_id = new UUIDMsg();
            this.feedback = new GoToPositionFeedback();
        }

        public GoToPositionFeedbackMessage(UUIDMsg goal_id, GoToPositionFeedback feedback)
        {
            this.goal_id = goal_id;
            this.feedback = feedback;
        }

        public static GoToPositionFeedbackMessage Deserialize(MessageDeserializer deserializer) => new GoToPositionFeedbackMessage(deserializer);

        private GoToPositionFeedbackMessage(MessageDeserializer deserializer)
        {
            this.goal_id = UUIDMsg.Deserialize(deserializer);
            this.feedback = GoToPositionFeedback.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal_id);
            serializer.Write(this.feedback);
        }

        public override string ToString()
        {
            return "GoToPositionFeedbackMessage: " +
                   "\ngoal_id: " + goal_id.ToString() +
                   "\nfeedback: " + feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}