//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoToPositionGoal : Message
    {
        public const string k_RosMessageName = "remora_interfaces/GoToPosition";
        public override string RosMessageName => k_RosMessageName;

        //  Goal - What we want to achieve
        public float target_x;
        public float target_y;

        public GoToPositionGoal()
        {
            this.target_x = 0.0f;
            this.target_y = 0.0f;
        }

        public GoToPositionGoal(float target_x, float target_y)
        {
            this.target_x = target_x;
            this.target_y = target_y;
        }

        public static GoToPositionGoal Deserialize(MessageDeserializer deserializer) => new GoToPositionGoal(deserializer);

        private GoToPositionGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target_x);
            deserializer.Read(out this.target_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_x);
            serializer.Write(this.target_y);
        }

        public override string ToString()
        {
            return "GoToPositionGoal: " +
            "\ntarget_x: " + target_x.ToString() +
            "\ntarget_y: " + target_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
