//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Action
{
    [Serializable]
    public class CancelGoalRequest : Message
    {
        public const string k_RosMessageName = "action_msgs/CancelGoal";
        public override string RosMessageName => k_RosMessageName;

        //  Cancel one or more goals with the following policy:
        // 
        //  - If the goal ID is zero and timestamp is zero, cancel all goals.
        //  - If the goal ID is zero and timestamp is not zero, cancel all goals accepted
        //    at or before the timestamp.
        //  - If the goal ID is not zero and timestamp is zero, cancel the goal with the
        //    given ID regardless of the time it was accepted.
        //  - If the goal ID is not zero and timestamp is not zero, cancel the goal with
        //    the given ID and all goals accepted at or before the timestamp.
        //  Goal info describing the goals to cancel, see above.
        public GoalInfoMsg goal_info;

        public CancelGoalRequest()
        {
            this.goal_info = new GoalInfoMsg();
        }

        public CancelGoalRequest(GoalInfoMsg goal_info)
        {
            this.goal_info = goal_info;
        }

        public static CancelGoalRequest Deserialize(MessageDeserializer deserializer) => new CancelGoalRequest(deserializer);

        private CancelGoalRequest(MessageDeserializer deserializer)
        {
            this.goal_info = GoalInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal_info);
        }

        public override string ToString()
        {
            return "CancelGoalRequest: " +
            "\ngoal_info: " + goal_info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
