//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommunicationInterfaces
{
    [Serializable]
    public class DoubleMessageMsg : Message
    {
        public const string k_RosMessageName = "communication_interfaces/DoubleMessage";
        public override string RosMessageName => k_RosMessageName;

        public double data;

        public DoubleMessageMsg()
        {
            this.data = 0.0;
        }

        public DoubleMessageMsg(double data)
        {
            this.data = data;
        }

        public static DoubleMessageMsg Deserialize(MessageDeserializer deserializer) => new DoubleMessageMsg(deserializer);

        private DoubleMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "DoubleMessageMsg: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
