//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommunicationInterfaces
{
    [Serializable]
    public class FloatArrayMsg : Message
    {
        public const string k_RosMessageName = "communication_interfaces/FloatArray";
        public override string RosMessageName => k_RosMessageName;

        public float[] floats;

        public FloatArrayMsg()
        {
            this.floats = new float[0];
        }

        public FloatArrayMsg(float[] floats)
        {
            this.floats = floats;
        }

        public static FloatArrayMsg Deserialize(MessageDeserializer deserializer) => new FloatArrayMsg(deserializer);

        private FloatArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.floats, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.floats);
            serializer.Write(this.floats);
        }

        public override string ToString()
        {
            return "FloatArrayMsg: " +
            "\nfloats: " + System.String.Join(", ", floats.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
