//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommunicationInterfaces
{
    [Serializable]
    public class Int8MessageMsg : Message
    {
        public const string k_RosMessageName = "communication_interfaces/Int8Message";
        public override string RosMessageName => k_RosMessageName;

        public sbyte data;

        public Int8MessageMsg()
        {
            this.data = 0;
        }

        public Int8MessageMsg(sbyte data)
        {
            this.data = data;
        }

        public static Int8MessageMsg Deserialize(MessageDeserializer deserializer) => new Int8MessageMsg(deserializer);

        private Int8MessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "Int8MessageMsg: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
