//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommunicationInterfaces
{
    [Serializable]
    public class OpinionMACMessageMsg : Message
    {
        public const string k_RosMessageName = "communication_interfaces/OpinionMACMessage";
        public override string RosMessageName => k_RosMessageName;

        public long id;
        public long opinion;
        public string mac;

        public OpinionMACMessageMsg()
        {
            this.id = 0;
            this.opinion = 0;
            this.mac = "";
        }

        public OpinionMACMessageMsg(long id, long opinion, string mac)
        {
            this.id = id;
            this.opinion = opinion;
            this.mac = mac;
        }

        public static OpinionMACMessageMsg Deserialize(MessageDeserializer deserializer) => new OpinionMACMessageMsg(deserializer);

        private OpinionMACMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.opinion);
            deserializer.Read(out this.mac);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.opinion);
            serializer.Write(this.mac);
        }

        public override string ToString()
        {
            return "OpinionMACMessageMsg: " +
            "\nid: " + id.ToString() +
            "\nopinion: " + opinion.ToString() +
            "\nmac: " + mac.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
