//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommunicationInterfaces
{
    [Serializable]
    public class OpinionMessageMsg : Message
    {
        public const string k_RosMessageName = "communication_interfaces/OpinionMessage";
        public override string RosMessageName => k_RosMessageName;

        public long id;
        public long opinion;

        public OpinionMessageMsg()
        {
            this.id = 0;
            this.opinion = 0;
        }

        public OpinionMessageMsg(long id, long opinion)
        {
            this.id = id;
            this.opinion = opinion;
        }

        public static OpinionMessageMsg Deserialize(MessageDeserializer deserializer) => new OpinionMessageMsg(deserializer);

        private OpinionMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.opinion);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.opinion);
        }

        public override string ToString()
        {
            return "OpinionMessageMsg: " +
            "\nid: " + id.ToString() +
            "\nopinion: " + opinion.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
