//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommunicationInterfaces
{
    [Serializable]
    public class RangeDataMsg : Message
    {
        public const string k_RosMessageName = "communication_interfaces/RangeData";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public float[] ranges;
        public double[] angles;

        public RangeDataMsg()
        {
            this.header = new Std.HeaderMsg();
            this.ranges = new float[0];
            this.angles = new double[0];
        }

        public RangeDataMsg(Std.HeaderMsg header, float[] ranges, double[] angles)
        {
            this.header = header;
            this.ranges = ranges;
            this.angles = angles;
        }

        public static RangeDataMsg Deserialize(MessageDeserializer deserializer) => new RangeDataMsg(deserializer);

        private RangeDataMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.ranges, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.angles, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.ranges);
            serializer.Write(this.ranges);
            serializer.WriteLength(this.angles);
            serializer.Write(this.angles);
        }

        public override string ToString()
        {
            return "RangeDataMsg: " +
            "\nheader: " + header.ToString() +
            "\nranges: " + System.String.Join(", ", ranges.ToList()) +
            "\nangles: " + System.String.Join(", ", angles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
