//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CommunicationInterfaces
{
    [Serializable]
    public class StringMessageMsg : Message
    {
        public const string k_RosMessageName = "communication_interfaces/StringMessage";
        public override string RosMessageName => k_RosMessageName;

        public string data;

        public StringMessageMsg()
        {
            this.data = "";
        }

        public StringMessageMsg(string data)
        {
            this.data = data;
        }

        public static StringMessageMsg Deserialize(MessageDeserializer deserializer) => new StringMessageMsg(deserializer);

        private StringMessageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "StringMessageMsg: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
