//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoalResultMsg : Message
    {
        public const string k_RosMessageName = "remora_interfaces/GoalResult";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;
        public float final_x;
        public float final_y;

        public GoalResultMsg()
        {
            this.success = false;
            this.message = "";
            this.final_x = 0.0f;
            this.final_y = 0.0f;
        }

        public GoalResultMsg(bool success, string message, float final_x, float final_y)
        {
            this.success = success;
            this.message = message;
            this.final_x = final_x;
            this.final_y = final_y;
        }

        public static GoalResultMsg Deserialize(MessageDeserializer deserializer) => new GoalResultMsg(deserializer);

        private GoalResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
            deserializer.Read(out this.final_x);
            deserializer.Read(out this.final_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
            serializer.Write(this.final_x);
            serializer.Write(this.final_y);
        }

        public override string ToString()
        {
            return "GoalResultMsg: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString() +
            "\nfinal_x: " + final_x.ToString() +
            "\nfinal_y: " + final_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
