//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RemoraInterfaces
{
    [Serializable]
    public class GoalFeedbackMsg : Message
    {
        public const string k_RosMessageName = "remora_interfaces/GoalFeedback";
        public override string RosMessageName => k_RosMessageName;

        public float current_x;
        public float current_y;
        public float distance_remaining;
        public float progress_percent;

        public GoalFeedbackMsg()
        {
            this.current_x = 0.0f;
            this.current_y = 0.0f;
            this.distance_remaining = 0.0f;
            this.progress_percent = 0.0f;
        }

        public GoalFeedbackMsg(float current_x, float current_y, float distance_remaining, float progress_percent)
        {
            this.current_x = current_x;
            this.current_y = current_y;
            this.distance_remaining = distance_remaining;
            this.progress_percent = progress_percent;
        }

        public static GoalFeedbackMsg Deserialize(MessageDeserializer deserializer) => new GoalFeedbackMsg(deserializer);

        private GoalFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_x);
            deserializer.Read(out this.current_y);
            deserializer.Read(out this.distance_remaining);
            deserializer.Read(out this.progress_percent);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_x);
            serializer.Write(this.current_y);
            serializer.Write(this.distance_remaining);
            serializer.Write(this.progress_percent);
        }

        public override string ToString()
        {
            return "GoalFeedbackMsg: " +
            "\ncurrent_x: " + current_x.ToString() +
            "\ncurrent_y: " + current_y.ToString() +
            "\ndistance_remaining: " + distance_remaining.ToString() +
            "\nprogress_percent: " + progress_percent.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
